#!/bin/bash
# For development, create a symlink to the local package directory

set -eu

. "$(dirname "${BASH_SOURCE[0]}")/setup" ${2}

TARGET_DIR="$(resolve-target "$1")"
SRC_DIR="$ROOT"
DEST_LINK="$TARGET_DIR/$PKG_PREFIX"

echo "Creating symlink for development in $TARGET_DIR"

TEMPLATE="$2"

if [[ -z "$TEMPLATE" ]]; then
  TEMPLATE="bachelor-thesis"
fi

if [[ ! -d "$ROOT/templates/$TEMPLATE" ]]; then
  echo "Template '$TEMPLATE' does not exist in '$ROOT/templates'."
  exit 1
fi

echo "Processing template $TEMPLATE"

if [ -e "$DEST_LINK/$VERSION" ]; then
  echo "Removing existing $DEST_LINK/$VERSION"
  rm -rf "$DEST_LINK/$VERSION"
fi
mkdir -p "$DEST_LINK"

ln -sf "$SRC_DIR" "$DEST_LINK/$VERSION"

if [ $? -eq 0 ]; then
  echo "Symlink created: $DEST_LINK/$VERSION to $SRC_DIR"
else
  echo "Error: Failed to create symlink $DEST_LINK/$VERSION" >&2
  exit 1
fi

cp -a "$ROOT/templates/$TEMPLATE/typst.toml" "$DEST_LINK/$VERSION"